chargebee/chargebee-flutter

README.md

updated following methods - retrieveProductIdentifers, retrieveEntitlements, retrieveAllPlans and retrieveAllItems.

OMNISUB-4750

---

CHANGELOG.md
README.md
ios/Classes/SwiftChargebeeFlutterSdkPlugin.swift
ios/chargebee_flutter.podspec
pubspec.yaml

Error while integrating iOS Flutter SDK

[Fix](Error while integrating iOS Flutter SDK)

---

CHANGELOG.md
README.md
android/build.gradle
android/src/main/kotlin/com/chargebee/flutter/sdk/ChargebeeFlutterSdkPlugin.kt
example/README.md
example/lib/main.dart
example/lib/product_listview.dart
ios/Classes/FlutterErrorHandler.swift
ios/Classes/SwiftChargebeeFlutterSdkPlugin.swift
ios/chargebee_flutter.podspec
lib/chargebee_flutter.dart
lib/src/chargebee.dart
lib/src/utils/cb_exception.dart
lib/src/utils/product.dart
pubspec.yaml

1. Chargebee.configure never finishes on error
2. Fixed CBEnvironment iOS build issue
3. Code refactor on chargebee wrapper class

[Fix](Github issue fixes)

---

CHANGELOG.md
README.md
android/build.gradle
ios/chargebee_flutter.podspec
pubspec.yaml

Fixed: App crash on signed apk and fixed in android native sdk v1.0.15

[Fix](App crash with NPE on signed build)

---

android/src/main/kotlin/com/chargebee/flutter/sdk/ChargebeeFlutterSdkPlugin.kt
ios/Classes/SwiftChargebeeFlutterSdkPlugin.swift

1. Tested purchase product and removed try block also empty checks for products
2. Made non-optional subscriptionId and planId to flutter object

[Fix](Reply already submitted and subscriptionId and planId made as non-optional)

---

android/src/main/kotlin/com/chargebee/flutter/sdk/ChargebeeFlutterSdkPlugin.kt
example/lib/product_listview.dart
ios/Classes/SwiftChargebeeFlutterSdkPlugin.swift
lib/src/chargebee.dart
lib/src/utils/product.dart

1. Product price has been updated as double value, before it was string type.
2. Added duration/subscriptionPeriod to Product class

[Fix](Product is lacking information)

---

CHANGELOG.md
README.md
android/build.gradle
android/src/main/kotlin/com/chargebee/flutter/sdk/ChargebeeFlutterSdkPlugin.kt
example/lib/main.dart
example/lib/product_listview.dart
ios/Classes/FlutterErrorHandler.swift
ios/Classes/SwiftChargebeeFlutterSdkPlugin.swift
ios/chargebee_flutter.podspec
pubspec.yaml

Error handling based on response code from Chargebee API and storekit/google billing error codes and also updated appropriate error messages

[Fix](app error handling)

---

lib/src/chargebee.dart
lib/src/constants.dart
lib/src/models/item.dart
lib/src/models/plan.dart
lib/src/models/product.dart

Updated inline comments for all the sdk methods as required

Updated inline comments

---

CHANGELOG.md
README.md
android/build.gradle
ios/chargebee_flutter.podspec
pubspec.yaml

Release v0.0.11

---

CHANGELOG.md
README.md
android/build.gradle
android/src/main/kotlin/com/chargebee/flutter/sdk/CBNativeError.kt
android/src/main/kotlin/com/chargebee/flutter/sdk/ChargebeeFlutterSdkPlugin.kt
example/integration_test/chargebee_test.dart
example/ios/StoreKit Configuration.storekit
example/lib/Constants.dart
example/lib/main.dart
ios/Classes/CBInAppSubscription+Extensions.swift
ios/Classes/FlutterErrorHandler.swift
ios/Classes/SwiftChargebeeFlutterSdkPlugin.swift
ios/chargebee_flutter.podspec
lib/chargebee_flutter.dart
lib/src/chargebee.dart
lib/src/constants.dart
lib/src/models/product.dart
lib/src/models/restore_subscription.dart
pubspec.yaml
test/chargebee_test.dart

[Feature] Restore Purchases

---

CHANGELOG.md
README.md
android/build.gradle
android/src/main/kotlin/com/chargebee/flutter/sdk/ChargebeeFlutterSdkPlugin.kt
example/integration_test/chargebee_test.dart
example/lib/main.dart
example/lib/network_connectivity.dart
example/lib/product_listview.dart
example/pubspec.yaml
ios/Classes/SwiftChargebeeFlutterSdkPlugin.swift
ios/chargebee_flutter.podspec
lib/chargebee_flutter.dart
lib/src/chargebee.dart
lib/src/constants.dart
lib/src/models/customer.dart
lib/src/models/item.dart
lib/src/models/plan.dart
lib/src/models/product.dart
lib/src/models/restore_subscription.dart
pubspec.yaml
test/chargebee_test.dart

Added cache retry mechanism for validate receipt.

Implemented retry mechanism for validate receipt

---

CHANGELOG.md
README.md
android/build.gradle
android/src/main/kotlin/com/chargebee/flutter/sdk/ChargebeeFlutterSdkPlugin.kt
example/lib/main.dart
example/lib/product_listview.dart
ios/Classes/SwiftChargebeeFlutterSdkPlugin.swift
ios/chargebee_flutter.podspec
lib/chargebee_flutter.dart
lib/src/chargebee.dart
lib/src/constants.dart
lib/src/models/product.dart
lib/src/models/product_type.dart
pubspec.yaml
test/chargebee_test.dart

**Feature**
- Added one time purchase support
- Adds cache retry mechanism for validating non-subscription product

One Time Purchase Support

---

CHANGELOG.md
README.md
android/build.gradle
android/src/main/kotlin/com/chargebee/flutter/sdk/ChargebeeFlutterSdkPlugin.kt
example/integration_test/chargebee_test.dart
example/lib/product_listview.dart
ios/Classes/SwiftChargebeeFlutterSdkPlugin.swift
ios/chargebee_flutter.podspec
lib/src/chargebee.dart
pubspec.yaml
test/chargebee_test.dart

**New Feature**
- Adds new API `purchaseStoreProduct` to purchase product with customer information.

Pass customer object to purchaseProduct method

---

CHANGELOG.md
README.md
android/build.gradle
android/src/main/kotlin/com/chargebee/flutter/sdk/ChargebeeFlutterSdkPlugin.kt
example/android/app/proguard-rules.pro
ios/chargebee_flutter.podspec
pubspec.yaml

The issue has fixed in native android sdk- https://github.com/chargebee/chargebee-android/pull/87

fix: android build issue on release mode.

---

CHANGELOG.md
README.md
android/build.gradle
ios/chargebee_flutter.podspec
pubspec.yaml

feat: Update google billing client

---

android/build.gradle

- Clone of #73, but on the `next` branch.

Make it compatible with AGP 8 (v1.0.0)

---

CHANGELOG.md
README.md
android/build.gradle
ios/chargebee_flutter.podspec
pubspec.yaml

Agp version main

---

CHANGELOG.md
README.md
android/build.gradle
ios/chargebee_flutter.podspec
pubspec.yaml

Compatible with AGP 8 - version number

Agp version next

---

README.md

https://mychargebee.atlassian.net/browse/OMNISUB-6373 - added customer object in parameter in restorepurchase method

OMNISUB-6373 - Update README.md

---

.github/workflows/secret.scan.yml

**Summary:**
This PR updates gitleaks workflow that automatically scans all pull requests for potential secrets (API keys, passwords, tokens, etc.).
**What’s included:**
- New workflow is independent of custom wrapper
- Updated workflow is triggered on every pull request similar to the custom cb wrapper.
**Notes:**
- No application code is affected.

workflow updated

---

CHANGELOG.md
README.md
android/build.gradle
ios/chargebee_flutter.podspec
pubspec.yaml

Update latest android sdk 1.2.3

Include latest chargebee-android with fix for retrofit proguard rules
